apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vbayqx2oa-python 
  janus-idp.io/tekton: vbayqx2oa-python
  backstage.io/kubernetes-id: vbayqx2oa-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vbayqx2oa-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml