apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vbayqx2oa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vbayqx2oa-python 
  name: vbayqx2oa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vbayqx2oa-python 
